apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfirst-deployment-3
  labels:
    app: app1
  annotations:
    kubernetes.io/change-cause: The initial rollout of myfirst-deployment
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 3
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      name: nginx-pod
      labels:
        app: app1
        tier: web
    spec:
      containers:
      - name: nginx
        image: nginx:1.22.0
        ports:
        - containerPort: 80