---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.100.238
  share: mnt/Pool-1
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4