# v1alpha2
apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: tkc-4
  namespace: ns-1
spec:
  topology:
    controlPlane:
      replicas: 1
      vmClass: best-effort-xsmall
      storageClass: wcp-storage-prolicy-1
      tkr:
        reference:
          name: v1.26.5---vmware.2-fips.1-tkg.1
          #name: v1.23.8---vmware.3-tkg.1
    nodePools:
    - name: worker-nodepool-a1
      replicas: 1
      vmClass: best-effort-xsmall
      storageClass: wcp-storage-prolicy-1
      tkr:
        reference:
          name: v1.26.5---vmware.2-fips.1-tkg.1
          #name: v1.23.8---vmware.3-tkg.1
          #name:  v1.26.13---vmware.1-fips.1-tkg.3