apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  volumes:
    - name: my-pvc
      persistentVolumeClaim:
        claimName: pvc-wcp-dynamic
  containers:
    - name: test-container
      image: nginx
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: my-pvc
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-wcp-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: wcp-storage-policy-1
  resources:
    requests:
        storage: 3Gi
        