apiVersion: v1
kind: Pod
metadata:
  name: pod-4-nginx-pvc
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: pvc-wcp-dynamic-2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-wcp-dynamic-2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: wcp-storage-policy-1
  resources:
    requests:
      storage: 1Gi
