# Verified by: 8.0U3 2025-01-09 
apiVersion: v1
kind: Pod
metadata:
  name: pod-3-ping
  namespace: default
spec:
  containers:
  - image: busybox:1.34
    name: busybox
    command: ["ping", "-c"]
    args: ["1", "8.8.8.8"]
  imagePullSecrets:
  - name: regcred
  restartPolicy: Never