# v1alpha2
# TKC-2-Photon
# Name: Chang WANG
# Date: 2025-01-06 
# CP*1 + WN*1 + VMFS
# Verified by: 8.0U3 2025-01-09

apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: tkc-2-photon
  namespace: ns-1
spec:
  topology:
    controlPlane:
      replicas: 1
      vmClass: best-effort-xsmall
      storageClass: wcp-storage-policy-1
      tkr:
        reference:
          #name: v1.23.8---vmware.3-tkg.1
          name: v1.26.12---vmware.2-fips.1-tkg.2
          #name: v1.27.10---vmware.1-fips.1-tkg.1.ubuntu
    nodePools:
    - name: worker-nodepool-1
      replicas: 1
      vmClass: best-effort-xsmall
      storageClass: wcp-storage-policy-1
      tkr:
        reference:
          #name: v1.23.8---vmware.3-tkg.1
          name: v1.26.12---vmware.2-fips.1-tkg.2
          #name:  v1.27.10---vmware.1-fips.1-tkg.1.ubuntu