---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
 storageClassName: wcp-vsan-policy
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: 3Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  labels:
    app: simple
spec:
  containers:
  - name: simple-pod
    image: "docker.io/busybox"
    volumeMounts:
    - name: block-vol
      mountPath: "/mnt/volume1"
    command: ["sleep", "1000000"]
  volumes:
    - name: block-vol
      persistentVolumeClaim:
        claimName: test-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: simple-svc
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: simple