# https://github.com/crccheck/docker-hello-world
# https://hub.docker.com/r/crccheck/hello-world
# This is a simple Docker image that just gives http responses on port 8000. It's small enough to fit on one floppy disk:
# Commands:
# curl 10.0.64.18:80
# curl -I 10.0.64.18:80
# curl -X POST 10.0.64.18:80/super/secret
# curl --write-out %{http_code} --silent --output /dev/null 10.0.64.18:80
---
apiVersion: v1
kind: Pod
metadata:
  name: hello-world-pod
  labels:
    app: hello-world
spec:
  containers:
  - name: hello-world-container
    image: "crccheck/hello-world"
    ports:
    - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: hello-world