# VMFS Datatore
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: tkg-vsan-sc
provisioner: csi.vsphere.vmware.com
allowVolumeExpansion: true
parameters:
  storagePolicyName: tkg-vsan-policy