#  vSAN Datastore
#  Name: Chang WANG
#  Date: 2025-01-06 
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: wcp-storage-policy-1
provisioner: csi.vsphere.vmware.com
allowVolumeExpansion: true
parameters:
  storagePolicyName: wcp-storage-policy-1